name: NPM Publish

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: test
        run: pnpm test && pnpm test:e2e

      - name: Install dependencies
        run: pnpm install && pnpm build

      - name: Publish to NPM
        shell: bash
        run: |
          npm config set "//registry.npmjs.org/:_authToken" "${{secrets.NPM_AUTH_TOKEN}}"
          npm config set "@teensy:registry" "https://registry.npmjs.org/"
          node -e "
          const pkg = require('./package.json')
          const rev = require('child_process')
            .execSync('git rev-parse --short=8 HEAD')
            .toString()
            .trim()
          pkg.version = pkg.version + '-next-' + rev
          require('fs').writeFileSync('./package.json', JSON.stringify(pkg, null, 2))
          "
      - run: npm publish --access=public --tag=next
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
